export const DURATION = {
  SPLASH_SCREEN: 1000,
  MENU_TOGGLE: 500,
  FAVORITES_DROP: 500,
  FAVORITES_MOVE: 250,
  FAVORITES_EDIT: 500,
  FAVORITES_GRID_ITEM: 500
};

export const DELAY = {
  SPLASH_SCREEN: 500,
  MENU_TOGGLE: 1500,
  FAVORITES_GRID_ITEM: 150,
  MAX_FAVORITES_APPEAR: 1000
};

export const INTERVAL = {
  FAVORITES_APPEAR: 75
};

export const TIMEOUT = {
  PAGINATION_TOGGLE: 1500
};
