export default {
  URL: 'https://pokeapi.co/api/v2',
  FETCH_SEARCH_ITEMS_PER_BATCH: 1000,
  FETCH_POKEMON_PER_BATCH: 10,
  FETCH_FAVORITES_PER_BATCH: 10,
  BATCH_FETCH_INTERVAL: 200, // ms
  POKEMON: {
    MAX_HEIGHT: 1000,
    MAX_WEIGHT: 10000,
    MAX_BASE_EXPERIENCE: 635,
    MAX_HP: 255,
    MAX_ATTACK: 190,
    MAX_DEFENSE: 250,
    MAX_SPECIAL_ATTACK: 194,
    MAX_SPECIAL_DEFENSE: 250,
    MAX_SPEED: 200
  }
};
