export enum ItemsActionType {
  FETCH_SINGLE_START = 'items/FETCH_SINGLE_START',
  FETCH_SINGLE_SUCCESS = 'items/FETCH_SINGLE_SUCCESS',
  FETCH_SINGLE_FAILURE = 'items/FETCH_SINGLE_FAILURE',
  FETCH_BATCH_START = 'items/FETCH_BATCH_START',
  FETCH_BATCH_SUCCESS = 'items/FETCH_BATCH_SUCCESS',
  FETCH_BATCH_FAILURE = 'items/FETCH_BATCH_FAILURE'
}
