export enum FavoriteActionType {
  SET_FAVORITES = 'favorites/SET_FAVORITES',
  SET_DISPLAYED_FAVORITES = 'favorites/SET_DISPLAYED_FAVORITES',
  ADD_TO_FAVORITES = 'favorites/ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES = 'favorites/REMOVE_FROM_FAVORITES'
};
